# Generated by Django 5.2.6 on 2025-10-04 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(default='System Admin', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('accuracy', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('target_muscle', models.CharField(max_length=100)),
                ('difficulty_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=50)),
                ('video_demo_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TherapyPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('duration_weeks', models.IntegerField()),
                ('exercises', models.ManyToManyField(related_name='therapy_plans', to='posture.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapy_plans', to='posture.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('device_type', models.CharField(choices=[('Webcam', 'Webcam'), ('Mobile', 'Mobile')], max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed')], max_length=50)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to='posture.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to='posture.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('generated_by', models.CharField(choices=[('Admin', 'Admin'), ('AI_Model', 'AI_Model')], max_length=50)),
                ('report_type', models.CharField(choices=[('Progress', 'Progress'), ('Accuracy', 'Accuracy'), ('Summary', 'Summary')], max_length=50)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='posture.customuser')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='posture.workoutsession')),
            ],
        ),
        migrations.CreateModel(
            name='Repetition',
            fields=[
                ('rep_id', models.AutoField(primary_key=True, serialize=False)),
                ('count_number', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('angle_left', models.FloatField()),
                ('angle_right', models.FloatField()),
                ('posture_accuracy', models.FloatField(help_text='Posture accuracy in %')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repetitions', to='posture.workoutsession')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_text', models.TextField()),
                ('accuracy_score', models.FloatField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('ai_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='posture.aimodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='posture.customuser')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='posture.workoutsession')),
            ],
        ),
    ]
