# Generated by Django 5.2.6 on 2026-03-11 20:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0003_adminreply_chatmessage_chatsession_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminreply',
            name='adminReply_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
