# Generated by Django 5.2.6 on 2025-10-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0004_alter_report_user_alter_feedback_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repetition',
            name='angle_left',
        ),
        migrations.RemoveField(
            model_name='repetition',
            name='angle_right',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/default-avatar.png', upload_to='profile_pics/'),
        ),
    ]
