# Generated by Django 5.2.6 on 2025-10-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0005_remove_repetition_angle_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='posture/images/default-avatar.png', null=True, upload_to='profile_pics/'),
        ),
    ]
