# Generated by Django 5.2.6 on 2026-04-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0005_trainingdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='exercise',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
