# Generated by Django 5.2.6 on 2026-01-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0005_remove_chatsession_updated_at_chatsession_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
