# Generated by Django 5.2.6 on 2026-04-18 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0006_aimodel_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='ai_model',
        ),
    ]
