# Generated by Django 5.2.6 on 2026-04-18 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0007_remove_feedback_ai_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='repetition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posture.repetition'),
        ),
    ]
