# Generated by Django 5.2.6 on 2025-10-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0007_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
