# Generated by Django 5.2.6 on 2025-10-10 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0008_aimodel_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='report_date',
            new_name='generated_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='report',
            name='json_data',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_type',
        ),
        migrations.AddField(
            model_name='report',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posture.exercise'),
        ),
        migrations.AddField(
            model_name='report',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
