# Generated by Django 5.2.6 on 2025-10-17 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0010_profile_created_at_profile_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='workoutsession',
            old_name='exercise',
            new_name='exercise_name',
        ),
        migrations.RenameField(
            model_name='workoutsession',
            old_name='user',
            new_name='username',
        ),
    ]
