# Generated by Django 5.2.6 on 2025-10-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0011_rename_user_feedback_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='name',
            new_name='exercise_name',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='user',
            new_name='username',
        ),
    ]
