# Generated by Django 5.2.6 on 2025-10-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0012_rename_name_exercise_exercise_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='workoutsession',
            old_name='exercise_name',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='workoutsession',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='report',
            name='username',
        ),
        migrations.AlterField(
            model_name='report',
            name='generated_by',
            field=models.CharField(choices=[('Admin', 'Admin'), ('AI_Model', 'AI_Model')], default='AI_Model', max_length=50),
        ),
    ]
