# Generated by Django 5.2.6 on 2025-10-17 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0013_rename_username_feedback_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
