# Generated by Django 5.2.6 on 2025-10-17 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0014_delete_admin'),
    ]

    operations = [
    ]
