# Generated by Django 5.2.6 on 2025-10-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0014_delete_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cookies_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
