# Generated by Django 5.2.6 on 2026-01-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0015_profile_cookies_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_flag',
            field=models.BooleanField(default=False),
        ),
    ]
