# Generated by Django 5.2.6 on 2026-01-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0016_profile_google_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
